# Generated by Django 3.2.9 on 2022-01-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.CharField(default='text', max_length=255),
            preserve_default=False,
        ),
    ]
