# Generated by Django 3.2.9 on 2022-01-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chat_privat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='privat',
            new_name='private',
        ),
    ]
